name: maven Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Maven
        run: mvn package

      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-jar
          path: target/*.jar